# Generated by Django 6.0.6 on 2026-07-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='содержимое')),
                ('picture', models.ImageField(upload_to='articles/', verbose_name='превью')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('is_publicated', models.BooleanField(default=False, verbose_name='признак публикац')),
                ('view_counter', models.PositiveIntegerField(default=0, verbose_name='количество просмотров')),
            ],
        ),
    ]
