# Generated by Django 6.0.6 on 2026-07-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_articles_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='picture',
            field=models.ImageField(upload_to='articles/', verbose_name='превью'),
        ),
    ]
