# Generated by Django 6.0.6 on 2026-07-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options_product_is_publicated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'description'], 'permissions': [('can_unpublish_product', 'Can unpublish product'), ('can_delete_products', 'Can delete product')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
